In [46]:
import typing
import random

import numpy as np

In [47]:
def sigmoid(x: np.floating):
    return 1 / (1 + np.exp(-x))

In [48]:
class Perceptron:
    def __init__(
        self,
        id: int,
        *,
        activation: typing.Callable[[np.floating], np.floating] = sigmoid
    ):
        self.id = id
        self.activation = activation

In [49]:
class DenseLayer:
    def __init__(self, n_perceptrons: int):
        self.perceptrons = [Perceptron(i) for i in range(n_perceptrons)]
        self.size = n_perceptrons

In [50]:
class InputLayer(DenseLayer):
    def __init__(self, n_perceptrons: int):
        super().__init__(n_perceptrons)

In [51]:
class Network:
    def __init__(self, layers: list[DenseLayer]):
        self.layers = layers
        self.weights: list[list[np.ndarray]] = self._initialize_random_weights()

    def _initialize_random_weights(self) -> list[list[np.ndarray]]:
        weights = []
        for idx, layer in enumerate(self.layers):
            next_layer = self.layers[idx + 1]

            intermediate_weights = []

            dim = layer.size + 1 # +1 for bias element
            num = next_layer.size

            for _ in range(num):
                # vec = np.random.uniform(0, 1, (1, dim))
                vec = np.array([random.random() for _ in range(dim)])
                intermediate_weights.append(vec)

            weights.append(intermediate_weights)

            if idx + 1 == len(self.layers) - 1:
                break
        
        return weights


In [52]:
nn = Network([
    InputLayer(2),
    DenseLayer(4),
    DenseLayer(2)
])

In [53]:
nn.weights

[[array([0.86790844, 0.96834797, 0.15993637]),
  array([0.35122612, 0.58513149, 0.14872007]),
  array([0.35887828, 0.67909424, 0.33210523]),
  array([0.95527097, 0.86995393, 0.18074543])],
 [array([0.13968463, 0.00826856, 0.3395287 , 0.39243069, 0.58516214]),
  array([0.53442484, 0.30436439, 0.61744243, 0.13276608, 0.13068895])]]